version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: librosdb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - libros_net

volumes:
  mariadb_data:

networks:
  libros_net:
